# ============================================
# pnpm Workspace Configuration
# ============================================

packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  axios: ^1.6.0
  next: ^14.0.0
  react: ^18.0.0
  react-dom: ^18.0.0
  express: ^4.18.0
  typescript: ^5.0.0
  prisma: ^5.0.0
  '@prisma/client': ^5.0.0
  '@types/node': ^20.0.0
  '@types/react': ^18.0.0
  '@types/express': ^4.17.0
